services:
  api:
    build:
      context: .
      dockerfile: dockerfiles/api/Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started
    ports:
      - "8000:8000"
    command: bash -c "uvicorn src.server.app:get_app --host 0.0.0.0 --port 8000 --factory"

  postgres:
    image: "postgis/postgis:latest"
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", $POSTGRES_DB]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d/